In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
#pip install xgboost

%matplotlib inline
sns.set_style("whitegrid")

In [2]:
train_X = pd.read_csv('D:/traindataset/traindataset/trainX.csv')
test_X = pd.read_csv('D:/traindataset/traindataset/testX.csv')
train_y = pd.read_csv('D:/traindataset/traindataset/trainY.csv')
validation_y = pd.read_csv('D:/traindataset/traindataset/validationY.csv')
validation_X = pd.read_csv('D:/traindataset/traindataset/validationX.csv')

In [3]:
display(train_X.head())
display(test_X.head())
display(train_y.head())
display(validation_y.head())
display(validation_X.head())

,Unnamed: 0,item_id,dept_id,cat_id,store_id,state_id,year,month,week,day,...,rolling_std_t7,rolling_mean_t30,rolling_mean_t90,rolling_mean_t180,rolling_std_t30,rolling_mean_t365,price_change_t1,price_change_t365,rolling_price_std_t7,rolling_price_std_t30
0,0,1437,3,1,0,0,2011,1,4,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1438,3,1,0,0,2011,1,4,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1439,3,1,0,0,2011,1,4,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1440,3,1,0,0,2011,1,4,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1441,3,1,0,0,2011,1,4,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Unnamed: 0,id,item_id,dept_id,cat_id,store_id,state_id,demand,part,date,...,rolling_mean_t180,rolling_mean_t365,rolling_std_t30,price_change_t1,price_change_t365,rolling_price_std_t7,rolling_price_std_t30,week,day,dayofweek
0,58327370,HOBBIES_1_001_CA_1_validation,1437,3,1,0,0,0,test,2016-04-25,...,0.7725,0.6600,0.9277,0.0,0.0,0.0,6.300000e-02,17,25,0
1,58327371,HOBBIES_1_002_CA_1_validation,1438,3,1,0,0,0,test,2016-04-25,...,0.3777,0.3562,0.4795,0.0,0.0,0.0,0.000000e+00,17,25,0
2,58327372,HOBBIES_1_003_CA_1_validation,1439,3,1,0,0,0,test,2016-04-25,...,0.6333,0.5015,1.1670,0.0,0.0,0.0,0.000000e+00,17,25,0
3,58327373,HOBBIES_1_004_CA_1_validation,1440,3,1,0,0,0,test,2016-04-25,...,1.9000,2.0140,2.0760,0.0,0.0,0.0,6.000000e-08,17,25,0
4,58327374,HOBBIES_1_005_CA_1_validation,1441,3,1,0,0,0,test,2016-04-25,...,1.1720,1.1120,0.9595,0.0,0.0,0.0,0.000000e+00,17,25,0

   Unnamed: 0  demand
0           0       0
1           1       0
2           2       0
3           3       0
4           4       0

   Unnamed: 0  demand
0    57473650       1
1    57473651       1
2    57473652       0
3    57473653       0
4    57473654       1

,Unnamed: 0,item_id,dept_id,cat_id,store_id,state_id,year,month,week,day,...,rolling_std_t7,rolling_mean_t30,rolling_mean_t90,rolling_mean_t180,rolling_std_t30,rolling_mean_t365,price_change_t1,price_change_t365,rolling_price_std_t7,rolling_price_std_t30
0,57473650,1437,3,1,0,0,2016,3,13,28,...,1.464,1.0000,0.8335,0.7110,1.2310,0.6440,0.0,0.0,0.0,0.000000e+00
1,57473651,1438,3,1,0,0,2016,3,13,28,...,0.378,0.1666,0.4000,0.3667,0.3792,0.3398,0.0,0.0,0.0,0.000000e+00
2,57473652,1439,3,1,0,0,2016,3,13,28,...,0.000,0.3000,0.6560,0.6610,0.4660,0.4822,0.0,0.0,0.0,0.000000e+00
3,57473653,1440,3,1,0,0,2016,3,13,28,...,2.115,2.2000,1.9220,1.8840,1.9550,2.0410,0.0,0.0,0.0,6.000000e-08
4,57473654,1441,3,1,0,0,2016,3,13,28,...,1.000,1.1340,1.1000,1.1880,1.3060,1.1260,0.0,0.0,0.0,0.000000e+00

In [4]:
#Save memory
def downcast(df):
    cols = df.dtypes.index.tolist()
    types = df.dtypes.values.tolist()
    for i,t in enumerate(types):
        if 'int' in str(t):
            if df[cols[i]].min() > np.iinfo(np.int8).min and df[cols[i]].max() < np.iinfo(np.int8).max:
                df[cols[i]] = df[cols[i]].astype(np.int8)
            elif df[cols[i]].min() > np.iinfo(np.int16).min and df[cols[i]].max() < np.iinfo(np.int16).max:
                df[cols[i]] = df[cols[i]].astype(np.int16)
            elif df[cols[i]].min() > np.iinfo(np.int32).min and df[cols[i]].max() < np.iinfo(np.int32).max:
                df[cols[i]] = df[cols[i]].astype(np.int32)
            else:
                df[cols[i]] = df[cols[i]].astype(np.int64)
        elif 'float' in str(t):
            if df[cols[i]].min() > np.finfo(np.float16).min and df[cols[i]].max() < np.finfo(np.float16).max:
                df[cols[i]] = df[cols[i]].astype(np.float16)
            elif df[cols[i]].min() > np.finfo(np.float32).min and df[cols[i]].max() < np.finfo(np.float32).max:
                df[cols[i]] = df[cols[i]].astype(np.float32)
            else:
                df[cols[i]] = df[cols[i]].astype(np.float64)
        elif t == np.object:
            if cols[i] == 'date':
                df[cols[i]] = pd.to_datetime(df[cols[i]], format='%Y-%m-%d')
            else:
                df[cols[i]] = df[cols[i]].astype('category')
    return df

In [5]:
submission=pd.read_csv('D:/sample_submission.csv')

In [6]:
from sklearn import preprocessing, metrics
import gc
import os

In [7]:
def reshape_and_merge(calendar, sell_prices, sales_train_validation, submission, merge=False):
    
    # , nrows=55000000
    sales_train_validation = pd.melt(sales_train_validation, id_vars = ['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'], var_name = 'day', value_name = 'demand')
    print('Reshaped sales_train_validation has {} rows and {} columns'.format(sales_train_validation.shape[0], sales_train_validation.shape[1]))
    
    test_rows = [row for row in submission['id'] if 'validation' in row]
    val_rows = [row for row in submission['id'] if 'evaluation' in row]
    test = submission[submission['id'].isin(test_rows)]
    val = submission[submission['id'].isin(val_rows)]
    
    test.columns = ['id', 'd_1914', 'd_1915', 'd_1916', 'd_1917', 'd_1918', 'd_1919', 'd_1920', 'd_1921', 
                    'd_1922', 'd_1923', 'd_1924', 'd_1925', 'd_1926', 'd_1927', 'd_1928', 'd_1929', 'd_1930', 
                    'd_1931', 'd_1932', 'd_1933', 'd_1934', 'd_1935', 'd_1936', 'd_1937', 'd_1938', 'd_1939', 
                    'd_1940', 'd_1941']
    val.columns = ['id', 'd_1942', 'd_1943', 'd_1944', 'd_1945', 'd_1946', 'd_1947', 'd_1948', 'd_1949', 
                   'd_1950', 'd_1951', 'd_1952', 'd_1953', 'd_1954', 'd_1955', 'd_1956', 'd_1957', 'd_1958', 
                   'd_1959', 'd_1960', 'd_1961', 'd_1962', 'd_1963', 'd_1964', 'd_1965', 'd_1966', 'd_1967', 
                   'd_1968', 'd_1969']
    
    product = sales_train_validation[['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id']].drop_duplicates()
    
    test = test.merge(product, how = 'left', on = 'id')
    val = val.merge(product, how = 'left', on = 'id')
    
    test = pd.melt(test, id_vars = ['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'], var_name = 'day', value_name = 'demand')
    val = pd.melt(val, id_vars = ['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'], var_name = 'day', value_name = 'demand')
    
    sales_train_validation['part'] = 'train'
    test['part'] = 'test'
    val['part'] = 'val'
    
    data = pd.concat([sales_train_validation, test, val], axis = 0)
    
    del sales_train_validation, test, val
    gc.collect()
    #data = data.loc[nrows:]
    
    data = data[data['part'] != 'val']

    if merge:
        data = pd.merge(data, calendar, how = 'left', left_on = ['day'], right_on = ['d'])
        data.drop(['d', 'day'], inplace = True, axis = 1)
        data = data.merge(sell_prices, on = ['store_id', 'item_id', 'wm_yr_wk'], how = 'left')
        print('The dataset finally has {} rows and {} columns'.format(data.shape[0], data.shape[1]))
    else: 
        pass
    
    return data

In [8]:
def transform(data):
    
    nan_features = [ 'event_type_1', 'event_name_2', 'event_type_2']
    for feature in nan_features:
        data[feature]=pd.Categorical(data[feature])
        data[feature].cat.add_categories('unknown',inplace=True)
        data[feature].fillna('unknown', inplace = True)
        
    cat = ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2']
    for feature in cat:
        encoder = preprocessing.LabelEncoder()
        data[feature] = encoder.fit_transform(data[feature])
    
    return data

In [28]:
#Selected features
#features = ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'year', 'month', 'week', 'day', 'dayofweek', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 
            #'snap_CA', 'snap_TX', 'snap_WI', 'sell_price']
features = ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id',  'month', 'day', 'dayofweek', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 
            'snap_CA', 'snap_TX', 'snap_WI', 'sell_price']

In [29]:
from sklearn.metrics import mean_absolute_error

In [30]:
train_X=downcast(train_X[features])
validation_X=downcast(validation_X[features])
test_X=downcast(test_X[features])

C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int16)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.float16)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int16)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.float16)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int16)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.int8)
C:\Users\qluaj\AppData\Local\Temp/ipykernel_8768/2168813802.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols[i]] = df[cols[i]].astype(np.float16)

In [26]:
train_y=train_y['demand']
train_y

0           0
1           0
2           0
3           0
4           0
           ..
57473645    0
57473646    0
57473647    1
57473648    4
57473649    5
Name: demand, Length: 57473650, dtype: int64

In [37]:
model = XGBRegressor(learning_rate=0.30,n_estimators=100)
model.fit(train_X,train_y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.3, max_delta_step=0,
             max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=6,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='approx', validate_parameters=1, verbosity=None)

In [38]:
predict_xgb=model.predict(validation_X)
validation_score=np.sqrt(mean_absolute_error(predict_xgb,validation_y))
validation_score

1.236938493445538

In [43]:
test_X = pd.read_csv('D:/traindataset/traindataset/testX.csv')

In [44]:
testPre_xgb=model.predict(test_X[features])

In [45]:
def submit_table(pred, test, submission):
    test['demand'] = pred
    predictions = test[['id', 'date', 'demand']]
    predictions = pd.pivot(predictions, index = 'id', columns = 'date', values = 'demand').reset_index()
    predictions.columns = ['id'] + ['F' + str(i + 1) for i in range(28)]
    evaluation_rows = [row for row in submission['id'] if 'evaluation' in row] 
    evaluation = submission[submission['id'].isin(evaluation_rows)]
    validation = submission[['id']].merge(predictions, on = 'id')
    final = pd.concat([validation, evaluation])
    final.to_csv('D:/submission.csv', index = False)

In [46]:
submit_table(testPre_xgb, test_X, submission)

In [47]:
def fit_xgbModel(train_X,train_y,validation_X,validation_y,lr=0.3,ne=100):
    model = XGBRegressor(learning_rate=lr,n_estimators=ne)
    model.fit(train_X,train_y)
    predict_xgb=model.predict(validation_X)
    validation_score=np.sqrt(mean_absolute_error(predict_xgb,validation_y))
    print('The learning rate is {} and the estimator number is {}. The validation score is {}.'.format(lr,ne,validation_score))
   
    return validation_score

In [48]:

learn_rate=[0.1,0.2]
n_est=[100]
val_score_list=[]
for l_r in learn_rate:
    for n_e in n_est:
        val_score=fit_xgbModel(train_X,train_y,validation_X,validation_y,lr=l_r,ne=n_e)

The learning rate is 0.1 and the estimator number is 100. The validation score is 1.2235598714236735.
The learning rate is 0.2 and the estimator number is 100. The validation score is 1.2152844831073437.

In [50]:
model = XGBRegressor(learning_rate=0.2,n_estimators=100)
model.fit(train_X,train_y)
predict_xgb=model.predict(validation_X)
validation_score=np.sqrt(mean_absolute_error(predict_xgb,validation_y))
testPre_xgb=model.predict(test_X[features])
submit_table(testPre_xgb, test_X, submission)