In [3]:
import pandas as pd
import numpy as np
import math

In [26]:
data=pd.read_csv('../data/GKX_20201231.csv')

In [27]:
data.head()

,permno,DATE,mvel1,RET,prc,SHROUT,beta,betasq,chmom,dolvol,...,baspread,ill,maxret,retvol,std_dolvol,std_turn,zerotrade,sic2,bm,bm_ia
0,10006,19260130,65400.0,0.032732,110.2500,600,NaN,NaN,NaN,NaN,...,0.006857,NaN,NaN,NaN,NaN,NaN,0.000066,NaN,NaN,NaN
1,10022,19260130,11200.0,0.017857,57.0000,200,NaN,NaN,NaN,NaN,...,0.018018,NaN,NaN,NaN,NaN,NaN,0.000003,NaN,NaN,NaN
2,10030,19260130,23400.0,0.161667,174.2500,156,NaN,NaN,NaN,NaN,...,0.004158,NaN,NaN,NaN,NaN,NaN,0.000023,NaN,NaN,NaN
3,10049,19260130,18500.0,0.141892,83.5000,250,NaN,NaN,NaN,NaN,...,0.006780,NaN,NaN,NaN,NaN,NaN,0.000022,NaN,NaN,NaN
4,10057,19260130,6125.0,-0.035714,11.8125,500,NaN,NaN,NaN,NaN,...,0.071795,NaN,NaN,NaN,NaN,NaN,0.000010,NaN,NaN,NaN

# 1. Select data from 1960 to 2019

In [28]:
data = data[(data['DATE'] >= 19600101) & (data['DATE'] <= 20191231)].reset_index(drop = True)
data

,permno,DATE,mvel1,RET,prc,SHROUT,beta,betasq,chmom,dolvol,...,baspread,ill,maxret,retvol,std_dolvol,std_turn,zerotrade,sic2,bm,bm_ia
0,10006,19600129,6.877300e+04,0.005155,48.750000,1418,1.158041,1.341058,-0.078184,9.474396,...,0.015272,2.059137e-07,0.033943,0.015149,0.591078,0.533983,9.859742e-08,37.0,NaN,NaN
1,10014,19600129,9.823500e+03,0.138889,5.125000,2183,1.838109,3.378645,-0.506541,7.946573,...,0.035918,1.906160e-06,0.028571,0.021261,0.491650,0.481666,8.535634e-08,NaN,NaN,NaN
2,10022,19600129,2.113375e+04,-0.045455,13.125000,1537,1.157077,1.338827,-0.374534,8.507143,...,0.022607,6.754297e-07,0.040000,0.026199,0.877110,1.639491,5.271194e-08,NaN,NaN,NaN
3,10030,19600129,8.120000e+04,-0.015000,49.250000,1624,1.327625,1.762587,-0.186923,9.550378,...,0.014960,4.355397e-07,0.038462,0.020206,0.936132,0.771756,1.102852e-07,NaN,NaN,NaN
4,10057,19600129,2.706250e+04,-0.020785,53.000000,500,1.194604,1.427080,-0.293635,8.138565,...,0.002941,3.479863e-07,0.018692,0.006685,0.451979,0.190010,9.545457e-01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3930469,93423,20191231,3.675103e+06,0.037489,45.110001,84524,0.986190,0.972570,0.082350,16.719505,...,0.024345,1.993666e-10,0.032511,0.015523,0.337361,5.211489,6.883089e-09,79.0,NaN,NaN
3930470,93426,20191231,4.300562e+05,-0.011915,34.000000,12498,1.441271,2.077263,-0.095066,12.908166,...,0.028999,6.936172e-09,0.070378,0.024943,0.498869,2.761443,1.867039e-08,36.0,NaN,NaN
3930471,93427,20191231,2.238312e+06,0.071913,64.839996,37003,1.129546,1.275875,0.609973,14.989790,...,0.025465,9.104732e-10,0.039481,0.019476,0.602190,6.208455,1.396611e-08,36.0,NaN,NaN
3930472,93434,20191231,7.526704e+04,-0.070796,2.100000,33305,0.636928,0.405677,-0.306626,8.623688,...,0.055040,1.254792e-06,0.112554,0.040972,0.772292,0.433168,2.360961e-07,1.0,NaN,NaN
3930473,93436,20191231,5.947004e+07,0.267897,418.329987,181062,1.007679,1.015416,1.253614,18.886064,...,0.025733,5.419624e-12,0.029506,0.021046,0.421723,18.833708,2.497297e-09,37.0,NaN,NaN

In [29]:
data['DATE']=data['DATE']//100 
data = data.rename(columns={'DATE': 'yyyymm'})#Let the DATE become the format "yyyymm"
data

,permno,yyyymm,mvel1,RET,prc,SHROUT,beta,betasq,chmom,dolvol,...,baspread,ill,maxret,retvol,std_dolvol,std_turn,zerotrade,sic2,bm,bm_ia
0,10006,196001,6.877300e+04,0.005155,48.750000,1418,1.158041,1.341058,-0.078184,9.474396,...,0.015272,2.059137e-07,0.033943,0.015149,0.591078,0.533983,9.859742e-08,37.0,NaN,NaN
1,10014,196001,9.823500e+03,0.138889,5.125000,2183,1.838109,3.378645,-0.506541,7.946573,...,0.035918,1.906160e-06,0.028571,0.021261,0.491650,0.481666,8.535634e-08,NaN,NaN,NaN
2,10022,196001,2.113375e+04,-0.045455,13.125000,1537,1.157077,1.338827,-0.374534,8.507143,...,0.022607,6.754297e-07,0.040000,0.026199,0.877110,1.639491,5.271194e-08,NaN,NaN,NaN
3,10030,196001,8.120000e+04,-0.015000,49.250000,1624,1.327625,1.762587,-0.186923,9.550378,...,0.014960,4.355397e-07,0.038462,0.020206,0.936132,0.771756,1.102852e-07,NaN,NaN,NaN
4,10057,196001,2.706250e+04,-0.020785,53.000000,500,1.194604,1.427080,-0.293635,8.138565,...,0.002941,3.479863e-07,0.018692,0.006685,0.451979,0.190010,9.545457e-01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3930469,93423,201912,3.675103e+06,0.037489,45.110001,84524,0.986190,0.972570,0.082350,16.719505,...,0.024345,1.993666e-10,0.032511,0.015523,0.337361,5.211489,6.883089e-09,79.0,NaN,NaN
3930470,93426,201912,4.300562e+05,-0.011915,34.000000,12498,1.441271,2.077263,-0.095066,12.908166,...,0.028999,6.936172e-09,0.070378,0.024943,0.498869,2.761443,1.867039e-08,36.0,NaN,NaN
3930471,93427,201912,2.238312e+06,0.071913,64.839996,37003,1.129546,1.275875,0.609973,14.989790,...,0.025465,9.104732e-10,0.039481,0.019476,0.602190,6.208455,1.396611e-08,36.0,NaN,NaN
3930472,93434,201912,7.526704e+04,-0.070796,2.100000,33305,0.636928,0.405677,-0.306626,8.623688,...,0.055040,1.254792e-06,0.112554,0.040972,0.772292,0.433168,2.360961e-07,1.0,NaN,NaN
3930473,93436,201912,5.947004e+07,0.267897,418.329987,181062,1.007679,1.015416,1.253614,18.886064,...,0.025733,5.419624e-12,0.029506,0.021046,0.421723,18.833708,2.497297e-09,37.0,NaN,NaN

# 2. Construct full dataset

In [30]:
macro = pd.read_csv('../data/macro.csv')
macro["Index"] = macro["Index"].apply(lambda x: float(x.replace(",", "")))
macro = macro.loc[(macro['yyyymm']>=196001)&(macro['yyyymm']<202001)]
macro

,yyyymm,Index,D12,E12,b/m,tbl,AAA,BAA,lty,ntis,Rfree,infl,ltr,corpr,svar,csp,CRSP_SPvw,CRSP_SPvwx
1068,196001,55.61,1.8667,3.3900,0.499502,0.0435,0.0461,0.0534,0.0441,0.022116,0.0033,-0.003401,0.0112,0.0107,0.000919,0.000889,-0.069933,-0.070835
1069,196002,56.12,1.9033,3.3900,0.493557,0.0396,0.0456,0.0534,0.0429,0.024037,0.0029,0.003413,0.0204,0.0128,0.001150,0.000661,0.013922,0.009129
1070,196003,55.34,1.9400,3.3900,0.549798,0.0331,0.0449,0.0525,0.0411,0.025593,0.0035,0.000000,0.0282,0.0191,0.000969,0.000361,-0.012566,-0.015238
1071,196004,54.37,1.9433,3.3467,0.563404,0.0323,0.0445,0.0520,0.0426,0.025577,0.0019,0.003401,-0.0170,-0.0022,0.000645,0.000121,-0.016113,-0.017097
1072,196005,55.83,1.9467,3.3033,0.541966,0.0329,0.0446,0.0528,0.0417,0.024414,0.0027,0.000000,0.0152,-0.0021,0.000424,-0.000036,0.033513,0.028312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,201908,2926.46,56.8388,133.6900,0.248539,0.0195,0.0298,0.0387,0.0163,-0.010142,0.0016,-0.000051,0.0797,0.0738,0.004318,NaN,-0.016085,-0.018377
1784,201909,2976.74,57.2195,132.9000,0.243797,0.0189,0.0303,0.0391,0.0170,-0.010838,0.0018,0.000783,-0.0192,-0.0190,0.000605,NaN,0.018791,0.017272
1785,201910,3037.56,57.5599,135.0900,0.242630,0.0165,0.0301,0.0392,0.0171,-0.013157,0.0015,0.002286,-0.0052,0.0006,0.001510,NaN,0.021621,0.020441
1786,201911,3140.98,57.9003,137.2800,0.233936,0.0154,0.0306,0.0394,0.0181,-0.007796,0.0012,-0.000536,-0.0059,0.0014,0.000306,NaN,0.036206,0.033979
1787,201912,3230.78,58.2406,139.4700,0.229944,0.0154,0.0301,0.0388,0.0186,-0.007199,0.0014,-0.000910,-0.0253,-0.0089,0.000502,NaN,0.029787,0.028136

## 2.1 Calculate some macropredictors that are not given directly
       Dividend to price ratio(dp):log(D12)-log(Index)
       Earnings-price ratio(ep):log(E12)-log(Index)
       Term spread(tms):lty-tbl
       Default spread(dfy):BAA-AAA

In [31]:
macro['dp'] = macro['D12'].apply(math.log) - macro['Index'].apply(math.log)
macro['ep'] = macro['E12'].apply(math.log) - macro['Index'].apply(math.log)
macro['tms'] = macro['lty']-macro['tbl']
macro['dfy'] = macro['BAA']-macro['AAA']
#Rename b/m by bm and Keep only 8 needed macropredictors
ned = ['yyyymm', 'dp', 'ep', 'bm', 'ntis', 'tbl', 'tms', 'dfy','svar']
macro = macro.rename(columns = {'b/m': 'bm'})[ned]

In [32]:
data = pd.merge(data, macro, how='left', on='yyyymm', suffixes=('', '_macro'))
data

,permno,yyyymm,mvel1,RET,prc,SHROUT,beta,betasq,chmom,dolvol,...,bm,bm_ia,dp,ep_macro,bm_macro,ntis,tbl,tms,dfy,svar
0,10006,196001,6.877300e+04,0.005155,48.750000,1418,1.158041,1.341058,-0.078184,9.474396,...,NaN,NaN,-3.394191,-2.797533,0.499502,0.022116,0.0435,0.0006,0.0073,0.000919
1,10014,196001,9.823500e+03,0.138889,5.125000,2183,1.838109,3.378645,-0.506541,7.946573,...,NaN,NaN,-3.394191,-2.797533,0.499502,0.022116,0.0435,0.0006,0.0073,0.000919
2,10022,196001,2.113375e+04,-0.045455,13.125000,1537,1.157077,1.338827,-0.374534,8.507143,...,NaN,NaN,-3.394191,-2.797533,0.499502,0.022116,0.0435,0.0006,0.0073,0.000919
3,10030,196001,8.120000e+04,-0.015000,49.250000,1624,1.327625,1.762587,-0.186923,9.550378,...,NaN,NaN,-3.394191,-2.797533,0.499502,0.022116,0.0435,0.0006,0.0073,0.000919
4,10057,196001,2.706250e+04,-0.020785,53.000000,500,1.194604,1.427080,-0.293635,8.138565,...,NaN,NaN,-3.394191,-2.797533,0.499502,0.022116,0.0435,0.0006,0.0073,0.000919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3930469,93423,201912,3.675103e+06,0.037489,45.110001,84524,0.986190,0.972570,0.082350,16.719505,...,NaN,NaN,-4.015896,-3.142629,0.229944,-0.007199,0.0154,0.0032,0.0087,0.000502
3930470,93426,201912,4.300562e+05,-0.011915,34.000000,12498,1.441271,2.077263,-0.095066,12.908166,...,NaN,NaN,-4.015896,-3.142629,0.229944,-0.007199,0.0154,0.0032,0.0087,0.000502
3930471,93427,201912,2.238312e+06,0.071913,64.839996,37003,1.129546,1.275875,0.609973,14.989790,...,NaN,NaN,-4.015896,-3.142629,0.229944,-0.007199,0.0154,0.0032,0.0087,0.000502
3930472,93434,201912,7.526704e+04,-0.070796,2.100000,33305,0.636928,0.405677,-0.306626,8.623688,...,NaN,NaN,-4.015896,-3.142629,0.229944,-0.007199,0.0154,0.0032,0.0087,0.000502
3930473,93436,201912,5.947004e+07,0.267897,418.329987,181062,1.007679,1.015416,1.253614,18.886064,...,NaN,NaN,-4.015896,-3.142629,0.229944,-0.007199,0.0154,0.0032,0.0087,0.000502

## 3. Fill the missing value with cross-sectional median or 0

In [33]:
nonpd = ['yyyymm','RET','SHROUT','mve0','prc','permno'] #Nonpredictors
macropd = ['dp','ep_macro','bm_macro','ntis','tbl','tms','dfy','svar'] #Macroeconomic predictors
sic2 = ['sic2'] #Industrial dummies
lst = nonpd + macropd + sic2
stockpd = [p for p in data.columns if p not in lst] #Stock-level predictors
len(stockpd)

94

In [34]:
period_list = np.unique(data['yyyymm'])
len(period_list)

720

In [ ]:
for pd in stockpd:
    c_row = 0
    for period in period_list:
        n_period = data[data['yyyymm'] == period].shape[0]
        #Compute the cross-sectional median of this stock predictor
        median = np.nanmedian(data.loc[c_row:(c_row+n_period-1),pd])
        #Fill missing values with median
        data.loc[c_row:(c_row+n_period-1),pd] = data.loc[c_row:(c_row+n_period-1),pd].replace(np.nan,median)
        c_row = c_row + n_period

In [36]:
newdt = data.fillna(0)

In [37]:
newdt = newdt.drop(columns=['prc','SHROUT','mve0']) #Drop the predictors that are not used
newdt.to_csv('../data/processed_data.csv', index = False)